spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k6s104.p.ssafy.io:3333/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssaffron
    password: ssafy123

  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: Asia/Seoul
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  cache:
    type: redis
  redis:
    host: "k6s104.p.ssafy.io"
    port: 8180
    password: ssafy123


server:
  port: 8081
