spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k6s104.p.ssafy.io:3333/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssaffron
    password: ssafy123

  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: Asia/Seoul
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  cache:
    type: redis
  redis:
    host: "k6s104.p.ssafy.io"
    port: 8180
    password: ssafy123

  jwt:
    header: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400

  output:
    ansi:
      enabled: always

logging:
  slack:
    webhook-uri: https://hooks.slack.com/services/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
  config: classpath:logback-spring.xml

server:
  port: 8081

