spring:
  main:
    allow-circular-references: true
  cache:
    type: redis
  redis:
    host: "k6s104.p.ssafy.io"
    port: 8180
    password: ssafy123

  jwt:
    header: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400

server:
  port: 8082
