spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k6s104.p.ssafy.io:3333/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: login_manager
    password: ssafyLoginManager123
  main:
    allow-circular-references: true
  cache:
    type: redis
  redis:
    host: "k6s104.p.ssafy.io"
    port: 8180
    password: ssafy123

  jwt:
    header: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8082
