server:
  port: 8083

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: http://localhost:8081,http://localhost:8082,http://localhost:3000
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

      routes:
        - id: all
          uri: http://localhost:8081
          predicates:
            - Path=/v1/api/member/signup,/v1/api/plan/month/**,/v1/api/plan/laundry/**,/v1/api/member/check/**
            - Method=POST,GET

        - id: auth
          uri: http://localhost:8082
          predicates:
            - Path=/v1/api/**
            - Method=GET,PUT,DELETE,POST
#          filters:
#            - name: AuthFilter
#              args:
#                baseMessage: Spring Cloud Gateway AuthFilter
#                preLogger: true
#                postLogger: true
#            - AddRequestHeader=redirect, http://localhost:3000/myInfo