server:
  port: 8083

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: http://localhost:8081
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

      routes:
        - id: all
          uri: http://localhost:8081
          predicates:
            - Path=/v1/api/member/signup,/v1/api/plan/month/**,/v1/api/plan/laundry/**
            - Method=POST,GET
        - id: auth
          uri: http://localhost:8082
          predicates:
            - Path=/v1/api/**
            - Method=GET,PUT,DELETE,POST